### ISSUE TITLE
域名证书已填，不知怎么安装

### ISSUE THREAD

**Issue by alias38** [ipuppet/IPAInstaller#2]
![image](https://github.com/ipuppet/IPAInstaller/assets/64385112/8a4c42b1-2ea2-4982-9613-6bc806903a9c)
![image](https://github.com/ipuppet/IPAInstaller/assets/64385112/daf12d71-c3ff-4079-9524-b2125f0d1483)
出现这样，请问设置有问题吗

**Comment by ipuppet** [comment]
证书和私钥分开填，key应该是

`-----BEGIN EC PRIVATE KEY-----`

开头的

**Comment by alias38** [comment]
> 证书和私钥分开填，key应该是
> 
> `-----BEGIN EC PRIVATE KEY-----`
> 
> 开头的

![image](https://github.com/ipuppet/IPAInstaller/assets/64385112/6d26d583-efc0-4e85-bde7-0522674aa940)
![image](https://github.com/ipuppet/IPAInstaller/assets/64385112/ecf8e9c9-bfe9-4475-8803-b06ae54243d0)
应该是对的吧
我用的是fullchain.cer
和域名.key
![image](https://github.com/ipuppet/IPAInstaller/assets/64385112/f64e01db-925f-40b2-9db8-f8bc4422fdd7)

**Comment by ipuppet** [comment]
应该是对的，你换其他的试试，不要有空格或空行。你看看有没有什么报错，在脚本编辑模式下运行会有控制台输出

**Comment by alias38** [comment]
> 在

好的，明天再试试

**Comment by alias38** [comment]
> 在

![image](https://github.com/ipuppet/IPAInstaller/assets/64385112/4e3d36f2-dd64-4ad5-b862-032fd7224733)

**Comment by ipuppet** [comment]
你的私钥前面少了两个减号

**Comment by alias38** [comment]
> 你的私钥前面少了两个减号
> 顺便看看你的证书后面是不是多了两个减号

正常了还是无法连接
![image](https://github.com/ipuppet/IPAInstaller/assets/64385112/c0c20849-a8ed-4626-8e91-8e7a3d06b70f)
![image](https://github.com/ipuppet/IPAInstaller/assets/64385112/6b1895e5-78f1-4c09-b6d2-32545cbc4f76)

**Comment by ipuppet** [comment]
可能还是证书的问题

**Comment by alias38** [comment]
> 可能还是证书的问题

证书已从服务器下载下来拷贝进去的，应该没有问题了。
就是域名解析需要添加A记录指向127.0.0.1吗？
还有就是软件包需不需要上传至服务器

**Comment by ipuppet** [comment]
需要解析到127.0.0.1，与服务器无关，这是个本地程序

**Comment by alias38** [comment]
> 需要解析到127.0.0.1，与服务器无关，这是个本地程序

好的，我换个域名试试吧

**Comment by alias38** [comment]
> 需要解析到127.0.0.1，与服务器无关，这是个本地程序

会不会跟nginx有关？
